import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import SyncUser from "./components/SyncUser";
import { GlobalLoadingProvider } from './components/GlobalLoadingProvider';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-black`}
        >
          {/* Sync Clerk user to DB when signed in */}
          <SyncUser />
          <GlobalLoadingProvider>
            {children}
          </GlobalLoadingProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
